name: Kotlin Header
on: workflow_dispatch

jobs:
  kotlin-header:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version: '1.26'

      - run: go install github.com/google/addlicense@latest

      - run: |
          YEAR=$(date +%Y)
          echo -e "Sonora Project ($YEAR)\nOriginal project attribution: Chartreux Westia (github.com/koiverse)\nMaintained by Susil (github.com/susil0311)\nLicensed under GPL-3.0 | see git history for contributors" > banner.txt

          find . -type f -name "*.kt" -exec grep -q "Licensed Under GPL-3.0" {} \; -exec sed -i '0,/\*\//d' {} \;

          find . -type f -name "*.kt" -print0 | xargs -0 -r addlicense -v -f banner.txt
          rm banner.txt

      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Kotlin Header
          
